-- Inventory Service Controller
RegisterServerEvent("vorpinventory:getItemsTable", InventoryService.getItemsTable)
RegisterServerEvent("vorpinventory:getInventory", InventoryService.getInventory)
RegisterServerEvent("vorpinventory:serverGiveItem", InventoryService.GiveItem)
RegisterServerEvent("vorpinventory:serverGiveWeapon", InventoryService.GiveWeapon)
RegisterServerEvent("vorpinventory:serverDropItem", InventoryService.DropItem)
RegisterServerEvent("vorpinventory:serverDropMoney", InventoryService.DropMoney)
RegisterServerEvent("vorpinventory:serverDropGold", InventoryService.DropGold)
RegisterServerEvent("vorpinventory:serverDropWeapon", InventoryService.DropWeapon)
RegisterServerEvent("vorpinventory:sharePickupServerItem", InventoryService.sharePickupServerItem)
RegisterServerEvent("vorpinventory:sharePickupServerWeapon", InventoryService.sharePickupServerWeapon)
RegisterServerEvent("vorpinventory:shareMoneyPickupServer", InventoryService.shareMoneyPickupServer)
RegisterServerEvent("vorpinventory:shareGoldPickupServer", InventoryService.shareGoldPickupServer)
RegisterServerEvent("vorpinventory:onPickup", InventoryService.onPickup)
RegisterServerEvent("vorpinventory:onPickupMoney", InventoryService.onPickupMoney)
RegisterServerEvent("vorpinventory:onPickupGold", InventoryService.onPickupGold)
RegisterServerEvent("vorpinventory:setUsedWeapon", InventoryService.usedWeapon)
RegisterServerEvent("vorpinventory:setWeaponBullets", InventoryService.setWeaponBullets)
RegisterServerEvent("vorpinventory:giveMoneyToPlayer", InventoryService.giveMoneyToPlayer)
RegisterServerEvent("vorpinventory:giveGoldToPlayer", InventoryService.giveGoldToPlayer)
RegisterServerEvent("vorp_inventory:useItem", InventoryService.UseItem)
RegisterServerEvent("vorp_inventory:MoveToCustom", InventoryService.MoveToCustom)
RegisterServerEvent("vorp_inventory:TakeFromCustom", InventoryService.TakeFromCustom)
RegisterServerEvent("vorp_inventory:MoveToPlayer", InventoryService.MoveToPlayer)
RegisterServerEvent("vorp_inventory:TakeFromPlayer", InventoryService.TakeFromPlayer)
RegisterNetEvent("vorpinventory:servergiveammo", InventoryService.serverGiveAmmo)
RegisterServerEvent("vorpinventory:updateammo", InventoryService.updateAmmo)
AddEventHandler("vorp_NewCharacter", InventoryService.onNewCharacter)

RegisterServerEvent("vorpinventory:updateSlot", InventoryService.UpdateSlot)
RegisterServerEvent("vorpinventory:mergeSlots", InventoryService.MergeSlots)
RegisterServerEvent("vorpinventory:splitSlot", InventoryService.SplitSlot)
RegisterServerEvent("vorpinventory:pickupFromDrop", InventoryService.PickupFromDrop)
RegisterServerEvent("vorpinventory:dropSwapSlot", InventoryService.DropSwapSlot)
RegisterServerEvent("vorpinventory:dropMergeSlot", InventoryService.DropMergeSlot)
RegisterServerEvent("vorpinventory:dropSplitSlot", InventoryService.DropSplitSlot)
RegisterServerEvent("vorpinventory:secondSwapSlot", InventoryService.SecondSwapSlot)
RegisterServerEvent("vorpinventory:secondMergeSlot", InventoryService.SecondMergeSlot)
RegisterServerEvent("vorpinventory:secondSplitSlot", InventoryService.SecondSplitSlot)

-- shared and for dev mode --
RegisterServerEvent("vorpCore:LoadAllAmmo")
AddEventHandler("vorpCore:LoadAllAmmo", InventoryService.LoadAllAmmo)
-------------------------
